### ISSUE TITLE
Please make it read an included image

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-comments#2]
Dear Friend
Why not read an image link, please add the feature read external image link and thank you very much.

![9999](https://user-images.githubusercontent.com/24383546/34531617-f696f84a-f0c3-11e7-9d56-d3ae3ad00e7f.png)

```
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
```

**Comment by phhpro** [comment]
The latest version includes optional  header and footer. Just edit the mark-up in these files to suit your needs.

**Comment by phhpro** [comment]
Hello there,

It's been a while, but I finally got around implementing an upload function. The same applies to PHP Atomchat, though slightly different. If you have a moment to test, I'd be happy to get some feedback on either PHP Easy Comments or PHP Atomchat; or both ;) Thanks.

**Comment by eArabic** [comment]
Hello dear friend
Thank you very much for the wonderful new update, I've tried it very well, upload photos great thank you very much for this update, great work, I was happy with this important update.

![999](https://user-images.githubusercontent.com/24383546/39111552-366643e8-46de-11e8-8675-ff98924aacd8.png)

**Comment by phhpro** [comment]
Glad to hear you like it -- and that it works. I take it from there you figured how to patch your path :) BTW: You can hard-code the default interface language in comments.php on line #64 -- $eco_lref = "ar";  to print all script messages in Arabic -- or per session from the top-right drop-down menu. I'll probably add a language token to the user config in the next release. Didn't quite think of it this time.
