### ISSUE TITLE
Disable new comments in Page?!

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-comments#4]
Hello dear friend
I apologize for the repetition of the request, but it is really an important and necessary feature which is to disable any new comments while retaining the old comments.
What I mean is that the old comments appear and that the system disables any new comments.
And please add a feature that the administrator has responded to a verified and distinguished account for any other comments.
I hope the idea is understandable. I have an explanation of the idea because of the translation and not knowing English.
Thank you so much .

**Comment by phhpro** [comment]
Hi. I'm between flights. Considering to add a "disable new comments" condition as soon as get into the next hotel.

**Comment by eArabic** [comment]
Thank you very much my dear friend, happy trip and happy travel.
best regards

**Comment by phhpro** [comment]
Hi. Good news. I've got the sourcres on standby and will push an update soon. Still on the road but should arrive later today.

**Comment by eArabic** [comment]
Thank you so much my dear friend

**Comment by phhpro** [comment]
Update is on

**Comment by eArabic** [comment]
Hello dear friend
Thank you very much for the update, very excellent.
Please add the feature to add more than one admin user here:
$ eco_apfx = "root";
$ eco_asfx = "root";
In order to add more than one user to control the page and replies from the administration.
For example, how do I make it work?
$ eco_apfx = "root,admin,administration";

**Comment by phhpro** [comment]
That'd be a little beyond the scope of this script as it would imply adding excessive bloat in the form of advanced user management, checking priviledges, etc. Hence the sole super user was and is the site owner, alone.

If you absolutely must have any such feature to manage something as trivial as simple comments you'll need to add the required code yourself. While I'm (obviously) open to suggestions, I have no intention to add multi-user or groupware features to a vanilla script aimed at a single user (admin) environment.

If you consider your own coding skills sufficient, I suggest you have a look into multi-dimensional or associative arrays, whichever suites your likes/needs and then focus on cross-checking with restricted.php before working out the actual conditional behaviour/s. Now, if that sounds Chinese your coding skills may be just a little insufficient.

Anything else, feel free to shoot me a line and I might (or not) consider it worth the trouble.
